### ISSUE TITLE
Can be removed?

### ISSUE THREAD

**Issue by josefglatz** [franzholz/debug_mysql_db#1]
https://github.com/franzholz/debug_mysql_db/blob/22f353656abbb6f9c4a9f83a02557db55e74ef51/Classes/Database/DatabaseConnection.php#L129

**Comment by franzholz** [comment]
The function query cannot be removed, because it is also part of the derived class \TYPO3\CMS\Typo3DbLegacy\Database\DatabaseConnection where it contains a call to $this->logDeprecation();. Those deprecation logs should be avoided.
